### ISSUE TITLE
Can't reproduce tutorial figures from the code given?

### ISSUE THREAD

**Issue by kerimoyle** [ABI-Tutorials/CellML-OpenCOR-PMR#13]
Hi all
I'm trying to replicate the behaviour of the tutorials using libcellml and am struggling with some of them.  For example, in the [sodium channel](https://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/cellml_encaps_and_inter.html) tutorial:

1) The second equation is confusing:
![image](https://user-images.githubusercontent.com/46887220/71080722-06b7c180-218e-11ea-934a-acdff99f9825.png)
 ... this isn't true, it equals 38.511?

2) There's only equation including `g_Na` is `Na_conductance=g_Na*pow(m, 3{dimensionless})*h;` which doesn't change its value from the initial condition of 120.  Where does the behaviour in the figure come from?

![image](https://user-images.githubusercontent.com/46887220/71081113-dde3fc00-218e-11ea-9575-67284ba784b8.png)

3) The initial conditions don't seem to make sense to me?  The initial `h` value is 0.6 but in the figures it looks closer to 0.8ish?  See: `var h: dimensionless {init: 0.6, pub: out};`

4) In the PDF the equation for Na_conductance has mismatched parentheses: 
    `Na_conductance=g_Na*pow(m, 3{dimensionless})*h);`
   and defines `E_Na` twice? How come that's allowed?

If anyone can help me understand what I'm missing that would be great :) Thanks!

**Comment by nickerso** [comment]
@kerimoyle, the "OpenCOR" link in the figure caption provides direct access to the SED-ML that reproduces (b). The initial value for h is confusing - on the first run you can see it start at 0.6 and then increase. Running it a second time it will be at a more "steady state" initial condition which is what is shown in the figure - just to make sure it is confusing :) 

The SED-ML and referenced CellML should be the canonical definition for this example, which more than likely does not match what is in the text.

**Comment by kerimoyle** [comment]
Thanks Andre.  Unfortunately for me that link launches OpenCOR then just sits there loading for ages without getting anywhere :(  I'm also a bit confused how running something repeatedly would change the output ... surely that means that the initial conditions are not really initial conditions but steady state?  Confusing, yep, I get that bit :)  Thoughts on the other points?

**Comment by nickerso** [comment]
Sounds like an OpenCOR issue to report :)

Re-running the simulation in OpenCOR will continue from the end of the previous simulation unless you reset the state of the model. So yes, it can be different in cases like this where the initial conditions are not the model at steady state.

regarding point (2) - I now see the confusion :) in that equation `g_Na` is actually the maximal conductance - a fixed parameter. And the `g_Na(t)` shown in the figures is actually the `Na_conductance` variable from that equation.

**Comment by kerimoyle** [comment]
I've tried again restarting from the final values of my initial simulation, and I still get behaviour quite different from this figure (albeit from a different starting point).  Are you able to access the SED-ML/CellML to email it to me so I can see where I'm going wrong?  I plot all the variables, and none of them look right, so I don't think it's just a labelling thing (unless they're swapped elsewhere inside the model too?)

**Comment by agarny** [comment]
FWIW, the OpenCOR link works fine for me (using the latest `2019-12-13` snapshot).

**Comment by kerimoyle** [comment]
OK, good to know.  I'll try updating mine in the morning and see what happens ... have there been big changes since June?

**Comment by agarny** [comment]
The biggest change is that OpenCOR now has Python support. However, since June, nothing has been done about running a model from an OpenCOR URL, so I am surprised that it's not working for you...!?

**Comment by kerimoyle** [comment]
To be honest, the OpenCOR bit isn't really relevant to me... I just need to
figure this model out so wanted the "real" version to sort out where things
were going wrong as the text here isn't correct.

**Comment by kerimoyle** [comment]
Can anyone please send me the files which are run for this model so I can check mine properly?

**Comment by kerimoyle** [comment]
I've found the problem.  The blocks of cellml text code in the instructions are suuuuuper-different from what's used to generate the figures:
- negatives are missing from exponential blocks and some constants
- missing constants in equations for alpha_h, beta_m
- the 25 in equation for alpha_m is 50 in the model
...
I'll make a PR and correct it.  Whew.
